name: Set CORS Headers

on:
  push:
    branches:
      - main  # 修改为你实际的分支名称

jobs:
  set-cors-headers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set CORS Headers
        run: |
          find . -type f -exec sed -i 's/^<\?xml version="1.0" encoding="UTF-8"\?>//g' {} \;
          find . -type f -exec sed -i 's/^<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">//g' {} \;
          find . -type f -exec sed -i 's/^<html xmlns="http://www.w3.org/1999/xhtml">/<html>/g' {} \;
          find . -type f -exec sh -c 'printf "Access-Control-Allow-Origin: *\n\n" | cat - {} > temp && mv temp {}' \;
      - name: Commit and Push Changes
        run: |
          git config --local user.email "your-email@example.com"  # 修改为你的邮箱
          git config --local user.name "Your Name"  # 修改为你的名字
          git add .
          git commit -m "Set CORS headers"
          git push origin main  # 修改为你实际的分支名称
